[tool.black]
target-version = ["py38"]
line-length = 120
include = '\.pyi?$'
exclude = '''
(
  /(
    \.git
    | migrations
    | venv
  )/
  | manage.py
)
'''


[tool.isort]
line_length = 120
profile = "black"
skip = [
    "venv",
    "venv_tmp",
    "migrations",
]
